//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class win0613Entities : DbContext
    {
        public win0613Entities()
            : base("name=win0613Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academic> Academics { get; set; }
        public virtual DbSet<Acount> Acounts { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<KindOfTopic> KindOfTopics { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessTopic> ProcessTopics { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeamWork> TeamWorks { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
