//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessTopic
    {
        public Nullable<bool> isPass { get; set; }
        public string processID { get; set; }
        public string topicID { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
