//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.ProcessTopics = new HashSet<ProcessTopic>();
            this.TeamWorks = new HashSet<TeamWork>();
        }
    
        public string TopicID { get; set; }
        public string name { get; set; }
        public string teacherID { get; set; }
        public string kotID { get; set; }
        public string facultyID { get; set; }
        public Nullable<System.DateTime> dateForm { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual KindOfTopic KindOfTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessTopic> ProcessTopics { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamWork> TeamWorks { get; set; }
    }
}
